### DISCUSSION TITLE
Jaspr Lint Quick Fix Not working

### DISCUSSION THREAD

**Discussion by TJMusiitwa** [schultek/jaspr#405] [Q&A]
Hey @schultek 
I have the latest `jaspr_lints` package installed and part of my dev dependencies. And with that I am getting several `sort_children_properties_last` lint warnings being raised. The docs mention that there is a quick fix available. However, when I hover over the bulb icon or just do a Save action in VS Code, this _fix_ is not applied.

Best course of action to address this, as going in and manually doing the edits in over **10** different files in my project, with **178** lint warnings reported seems a bit too much.

**Jaspr Doctor Output**

> [✓] Jaspr CLI (Version 0.18.0)
>   • Dart Version 3.7.2 (stable) (Tue Mar 11 04:27:50 2025 -0700) on "macos_arm64" at /Users/jonathan/development/flutter/bin/cache/dart-sdk/bin/dart
>   • Running on macos Version 14.1.2 (Build 23B92) - Locale en-GB
>   • Analytics: Enabled
> 
> [✓] Current Project
>   • Dependencies on core packages:
>     • jaspr: ^0.18.0
>     • jaspr_builder: ^0.18.0 (dev)
>   • Rendering mode: static
>   • Uses jaspr compilers: false
>   • Uses flutter embedding: false

  
  **Pubspec.yaml**
```
environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  jaspr: ^0.18.0

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.3
  flutter_lints: ^5.0.0
  jaspr_builder: ^0.18.0
  jaspr_lints: ^0.3.1
  # jaspr_tailwind: ^0.3.1

jaspr:
  mode: static
```
