### ISSUE TITLE
Tailwind css config issue (The system cannot find the file specified.)

### ISSUE THREAD

**Issue by shiwam77** [schultek/jaspr#289]
After installing tailwind css with this command

curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-<your-platform>

Command tailwindcss -h its working
Output:
C:\Users\ayusha>tailwindcss -h

tailwindcss v3.4.10

Usage:
tailwindcss [--input input.css] [--output output.css] [--watch] [options...]
tailwindcss init [--full] [--postcss] [options...]

index.html
```<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="scaffolded-by" content="https://github.com/schultek/jaspr">

        <title>student_management_system</title>
        <link rel="stylesheet" href="styles.css"/>
        <!--
            Loads and runs the compiled 'main.dart' file,
            can be changed to any other .dart file inside /web.
        -->
        <script defer src="main.dart.js"></script>
    </head>
    <body>
        <!-- Your app component will be inserted here. -->
    </body>
</html>
```
File architecture:
web < styles.tw.css

```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Where i am doing wrong here ??

This is my pubspec.yaml

```
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
     sdk: flutter
  jaspr: ^0.15.0
  jaspr_flutter_embed: ^0.3.4
  jaspr_router: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.0.10
  jaspr_builder: ^0.15.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  jaspr_tailwind: ^0.3.0

jaspr:
  mode: client

flutter:
  uses-material-design: true
```
Error
```
[BUILDER] [ERROR] ProcessException: The system cannot find the file specified.
[BUILDER] [ERROR]
[BUILDER] [ERROR] Command: tailwindcss --input C:\Users\ayusha\AppData\Local\Temp\scratch_space6a2d55f2\web\styles.tw.css --output C:/Users/ayusha/AppData/s[BUILDER] [ERROR] Failed after 2m 47s
[CLI] [ERROR] Failed building web assets. There is probably more output above.
[BUILDER] [ERROR] ProcessException: The system cannot find the file specified.
[BUILDER] [ERROR] 
[BUILDER] [ERROR] Command: tailwindcss --input C:\Users\ayusha\AppData\Local\Temp\scratch_space6a2d55f2\web\styles.tw.css --output C:/Users/ayusha/AppData/Local/Temp/scratch_space6a2d55f2/web/styles.css --confs
[BUILDER] [ERROR] Failed after 2.4s
[CLI] [ERROR] Failed building web assets. There is probably more output above.
```
