### ISSUE TITLE
Unavailable "dart:ui" package is imported through shared_preferences

### ISSUE THREAD

**Issue by kylianSalomon** [schultek/jaspr#351]
**Description**

Instanciating a shared_preferences class fails due to import of the unavailable librairy: "dart:ui".

**Additional Context**

I tried to implement the use of the shared_preferences packages following your example project flutter_plugin_interop but I keep getting this error while launching the server :

```
[SERVER] [ERROR] ../../../Development/flutter/packages/flutter/lib/src/foundation/binding.dart:18:8: Error: Dart library 'dart:ui' is not available on this platform.
[SERVER] [ERROR] import 'dart:ui' as ui show Brightness, PlatformDispatcher, SingletonFlutterWindow, window;
[SERVER] [ERROR] ^
[SERVER] [ERROR] Context: The unavailable library 'dart:ui' is imported through these packages:
[SERVER] [ERROR] 
[SERVER] [ERROR] server_target.dart => package:my_resume_web => package:shared_preferences => package:flutter => dart:ui
[SERVER] [ERROR] server_target.dart => package:my_resume_web => package:shared_preferences => package:shared_preferences_platform_interface => package:flutter => dart:ui
[SERVER] [ERROR] ...
[SERVER] [ERROR] 
```

This is my pubspec : 

```yaml
name: my_resume_web
description: A new jaspr project.
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_mappable: ^4.3.0
  dio: ^5.7.0
  envied: ^1.0.0
  jaspr: ^0.16.2
  jaspr_riverpod: ^0.3.16
  jaspr_router: ^0.6.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.13
  jaspr_web_compilers: ^4.0.10+1
  jaspr_builder: ^0.16.2
  jaspr_lints: ^0.1.2
  lints: ^3.0.0
  dart_mappable_builder: ^4.3.0
  envied_generator: ^1.0.0

jaspr:
  mode: static
```

And the jaspr doctor is normal.

Let me know if I missed some configurations of specifics topics related to the used of those kind of packages.

Thanks for your help.
