### ISSUE TITLE
PathNotFoundException: Cannot open file, path = '/tmp/scratch_spaceLIKFFN/web/styles.css'

### ISSUE THREAD

**Issue by devberkay** [schultek/jaspr#362]
I followed the instructions on docs for client side + jaspr_tailwind setup and everything **works perfectly fine on local** with `jaspr serve` and can take a **succesful build on local** with `jaspr build` but when i try to deploy to github pages with github actions, i am getting following error:

``Error: R] [ERROR] PathNotFoundException: Cannot open file, path = '/tmp/scratch_spaceLIKFFN/web/styles.css' (OS Error: No such file or directory, errno = 2)``

Below is my github actions' static.yml:

```
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: "Setup Dart"
        uses: dart-lang/setup-dart@v1.3
      - name: "Build Jaspr"
        run: |
          dart pub global activate jaspr_cli
          jaspr build --verbose
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'build/jaspr'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

I feel like i might need an extra step in my github action for tailwind, not sure if that's the case tho.

**Steps To Reproduce**

1. Follow the instructions for creating a jaspr client side project + jaspr_tailwind setup [here](https://docs.page/schultek/jaspr/eco/tailwind)
2. Follow the instructions for github pages deployment [here](https://docs.page/schultek/jaspr/concepts/deploying#github-pages)

**Comment by devberkay** [comment]
Yes, it was happening due to the missing tailwind step in the github action. Below is my setup w/ added tailwind config step and perfectly deployed. 🚀

```
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install Tailwind CSS
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          sudo mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss
      - name: "Setup Dart"
        uses: dart-lang/setup-dart@v1.3
      - name: "Build Jaspr"
        run: |
          dart pub global activate jaspr_cli
          jaspr build --verbose
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'build/jaspr'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

```
