### ISSUE TITLE
Problem following the Quick Start Guide: FormatException: Scheme not starting with alphabetic character (at character 1) 

### ISSUE THREAD

**Issue by timbrueckner** [schultek/jaspr#58]
I started with the quick start guide on https://docs.page/schultek/jaspr/quick-start. I created a project using the basic template, entered the working directory and ran the `serve` command. I did not open the project in an IDE or edited any files.

When the page is up, I open the browser and visit `localhost:8080`. I see a white page with »Hello World«, but an error gets logged on the server. It seems as if there is an `@` symbol in front of the scheme in the generated code.

FormatException: Scheme not starting with alphabetic character (at character 1) 

```
ERROR - 2023-03-31 17:36:08.922166

GET /@http://localhost:8080/app.app.dart.bootstrap.js
Error thrown by handler.
FormatException: Scheme not starting with alphabetic character (at character 1)
@http://localhost:8080/app.app.dart.bootstrap.js
^


dart:core                                           _SimpleUri.resolve
package:shelf_proxy/shelf_proxy.dart 42:28          proxyHandler.<fn>
package:jaspr/src/server/server_handler.dart 51:28  _webdevProxyHandler.<fn>
package:jaspr/src/server/server_handler.dart 34:55  RefreshableHandler.call
package:shelf_gzip/src/gzip_encoding.dart 44:44     createGzipMiddleware.<fn>.<fn>.<fn>
dart:async                                          new Future.sync
package:shelf_gzip/src/gzip_encoding.dart 44:21     createGzipMiddleware.<fn>.<fn>
```

This is my `pubspec.yaml`:

```
name: jaspr_website
description: A basic pure-dart web app with ssr & automatic client hydration.
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  jaspr: ^0.2.0+4

dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.1
  jaspr_builder: ^0.2.0
  lints: ^2.0.1
```

`jaspr --version` returns 0.1.0
`dart --version` returns Dart SDK version: 2.19.6 (stable)

I am using Safari on macOS.
